apiVersion: v2
name: onix-bap
description: A Helm chart for ONIX BAP adapter deployment (REST API)
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - onix
  - bap
  - ev-charging
maintainers:
  - name: NBSL TEAM
