apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-bap-rabbitmq.fullname" . }}-config
  labels:
    {{- include "mock-bap-rabbitmq.labels" . | nindent 4 }}
data:
  config.yml: |
{{ toYaml .Values.config | indent 4 }}
