apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-registry.fullname" . }}-config
  labels:
    {{- include "mock-registry.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}

