version: '3.9'

services:

  redis-bap:
    image: redis:7-alpine
    container_name: redis-bap
    ports:
      - "6379:6379"
    networks:
      - onix-bap-kafka
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - onix-bap-kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  onix-bap-kafka-plugin:
    image: manendrapalsingh/onix-adapter:latest
    pull_policy: always
    container_name: onix-bap-plugin-kafka
    ports:
      - "8001:8001"
    volumes:
      - /Users/localadmin/Project/NPCI/ev_charging_network/docker_plugin/kafka/docker-bap-kafka-plugin/config:/app/config/message-baised/kafka/onix-bap
      - /Users/localadmin/Project/NPCI/ev_charging_network/schema:/app/schemas:ro
    environment:
      CONFIG_FILE: /app/config/message-baised/kafka/onix-bap/adapter.yaml
    depends_on:
      redis-bap:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - onix-bap-kafka
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-bap
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: bap
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - onix-bap-kafka
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

volumes:
  kafka-data:
    driver: local

networks:
  onix-bap-kafka:
    driver: bridge

